name: phd_venv
channels:
  - conda-forge
  - defaults
dependencies:
  - blosc=1.21.6=hd145fbb_1
  - brotli-python=1.2.0=py311h55b82c4_0
  - bzip2=1.0.8=h500dc9f_8
  - c-ares=1.34.5=hf13058a_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py311h26bcf6e_1
  - cftime=1.6.4=py311h0e52b60_2
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hdf4=4.2.15=h8138101_7
  - hdf5=1.14.6=nompi_hc8237f9_103
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - krb5=1.21.3=h37d8d59_0
  - libaec=1.1.4=ha6bc127_0
  - libblas=3.9.0=38_he492b99_openblas
  - libcblas=3.9.0=38_h9b27e0a_openblas
  - libcurl=8.17.0=h7dd4100_0
  - libcxx=21.1.5=h3d58e20_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libev=4.33=h10d778d_2
  - libexpat=2.7.1=h21dd04a_0
  - libffi=3.5.2=h750e83c_0
  - libgfortran=15.2.0=h306097a_1
  - libgfortran5=15.2.0=h336fb69_1
  - libiconv=1.18=h57a12c2_2
  - libjpeg-turbo=3.1.2=h8616949_0
  - liblapack=3.9.0=38_h859234e_openblas
  - liblzma=5.8.1=hd471939_2
  - libnetcdf=4.9.3=nompi_habf9e57_103
  - libnghttp2=1.67.0=h3338091_0
  - libopenblas=0.3.30=openmp_h6006d49_3
  - libsqlite=3.51.0=h86bffb9_0
  - libssh2=1.11.1=hed3591d_0
  - libxml2=2.15.1=h23bb396_0
  - libxml2-16=2.15.1=h0ad03eb_0
  - libzip=1.11.2=h31df5bb_0
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=21.1.5=h472b3d1_0
  - lz4-c=1.10.0=h240833e_1
  - ncurses=6.5=h0622a9a_3
  - netcdf4=1.7.3=nompi_py311h56167b5_100
  - numpy=2.3.4=py311hf157cb9_0
  - openssl=3.6.0=h230baf5_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311hca9a5ca_1
  - pip=25.3=pyh8b19718_0
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.14=h74c2667_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - readline=8.2=h7cca4af_2
  - requests=2.32.5=pyhd8ed1ab_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h25c286d_0
  - tk=8.6.13=hf689a15_2
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xarray=2025.10.1=pyhcf101f3_1
  - zlib=1.3.1=hd23fc13_2
  - zstandard=0.25.0=py311h62e9434_1
  - zstd=1.5.7=h8210216_2
  - pip:
      - phd-project==0.1.0
prefix: /opt/miniconda3/envs/phd_venv
