name: phd_venv
channels:
  - conda-forge
dependencies:
  ########################################
  # Core interpreters
  ########################################
  - python=3.12
  - r-base>=4.3
  - r-essentials            # tidyverse, devtools, knitr, etc.

  ########################################
  # ---- R packages via conda ----
  ########################################
  - r-tidyverse
  - r-data.table
  - r-devtools
  - r-rmarkdown
  - r-lwgeom
  - r-sf
  - r-terra
  - r-units
  - r-lubridate
  # (ausplotsR will be installed from CRAN inside R)

  ########################################
  # ---- System geospatial libraries ----
  ########################################
  - gdal
  - proj
  - geos
  - hdf5
  - netcdf4
  - libxml2
  - udunits2
  - libgfortran
  - curl

  ########################################
  # ---- Python geospatial stack ----
  ########################################
  - geopandas
  - shapely
  - rasterio
  - rioxarray
  - pyproj
  - fiona
  - cartopy
  - folium

  ########################################
  # ---- Climate + NetCDF + Analysis ----
  ########################################
  - xarray
  - netcdf4
  - cftime
  - dask
  - zarr
  - bottleneck
  - h5netcdf
  - hdf5

  ########################################
  # ---- Scientific computing ----
  ########################################
  - numpy
  - pandas
  - scipy

  ########################################
  # ---- Visualisation ----
  ########################################
  - matplotlib
  - seaborn
  - plotly
  - hvplot
  - holoviews

  ########################################
  # ---- Jupyter environment ----
  ########################################
  - jupyterlab
  - ipykernel
  - nodejs

  ########################################
  # ---- Optional GIS utilities ----
  ########################################
  - qgis  # Remove if you don't want a full GIS

  ########################################
  # ---- Git support ----
  ########################################
  - git

  ########################################
  # ---- pip section (if needed) ----
  ########################################
  - pip
  - pip:
      # add extra pip-only packages here if needed
      - intake
      - intake-xarray
